-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg14lXDdqTeuXVJNZwh84HSZz1f4pmjB2MJfSDwPC4ZM2gCgYIKoZIzj0DAQehRANCAAS8CHILUzUVVxV3mLKDsI7sB/tBRKMK3ujMJUHC8fpiUQpHTl8tKlN/tXCGwUFd5xyiJ8sVEcY5EsgN4MR4xulO
-----END PRIVATE KEY-----